#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${MIGRATE_USER}') THEN
            CREATE ROLE ${MIGRATE_USER} LOGIN PASSWORD '${MIGRATE_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
        END IF;

        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${APP_USER}') THEN
            CREATE ROLE ${APP_USER} LOGIN PASSWORD '${APP_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
        END IF;
    END
    \$\$;

    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${MIGRATE_USER};
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_USER};

    GRANT USAGE, CREATE ON SCHEMA public TO ${MIGRATE_USER};
    GRANT USAGE ON SCHEMA public TO ${APP_USER};

    ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATE_USER} IN SCHEMA public
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_USER};
    ALTER DEFAULT PRIVILEGES FOR ROLE ${MIGRATE_USER} IN SCHEMA public
        GRANT USAGE, SELECT ON SEQUENCES TO ${APP_USER};
EOSQL

echo "PostgreSQL roles ${MIGRATE_USER} and ${APP_USER} initialized."
